algorithm: fullysupervised
save_dir: ./saved_models/usb_cv
save_name: fullysupervised_photo_200000_lr5e5
resume: False
load_path: ./saved_models/usb_cv/fullysupervised_photo_200000_lr5e5/latest_model.pth
overwrite: True
use_tensorboard: True
epoch: 200
num_train_iter: 200000
num_eval_iter: 2048
num_log_iter: 256
batch_size: 16
eval_batch_size : 16
num_warmup_iter: 5000
num_labels: 700000
uratio: 1
ema_m: 0.999
ema_p: 0.999
hard_label: True
T: 0.5
thresh_warmup: True
ulb_loss_ratio: 1
img_size: 224
crop_ratio: 0.875
optim: AdamW
lr: 5e-5
momentum: 0.9
weight_decay: 5e-4
amp: False
clip: 0.0
net: vit_small_patch16_224
net_from_name: False
data_dir: ./data
dataset: photo
train_sampler: RandomSampler
num_classes: 7
num_workers: 4
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10001
dist_backend: nccl
gpu: 0
use_pretrain: True
pretrain_path: https://github.com/microsoft/Semi-supervised-learning/releases/download/v.0.0.0/vit_small_patch16_224_mlp_im_1k_224.pth
ema: True