algorithm: dominomatch
save_dir: ./saved_models/usb_cv/
save_name: dominomatch_pacs_photo_10label_cyclemix_2
resume: False
load_path: ./saved_models/usb_cv/dominomatch_pacs_photo_10label_cyclemix_2/model_best.pth
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 10
num_train_iter: 10000
num_log_iter: 256
num_eval_iter: 2048
batch_size: 16
eval_batch_size: 64
num_warmup_iter: 5120
num_labels: 70
uratio: 1
ema_m: 0.00
hard_label: True
T: 0.5
p_cutoff: 0.90
ema_p: 0.999
ent_loss_ratio: 0.005
ulb_loss_ratio: 1.0
crossdomain_loss_ratio: 0.0
contrastive_loss_ratio: 0.001
warmup_kl_iter: 4096
warmup_contrastive_iter: 0
img_size: 224
crop_ratio: 0.875
optim: AdamW
lr: 0.0005
layer_decay: 0.5
momentum: 0.9
weight_decay: 0.0005
amp: False
clip: 0.0
use_ema: True
use_cat: True
net: vit_small_patch16_224
net_from_name: False
data_dir: ./data
dataset: pacs
train_sampler: RandomSampler
num_classes: 7
num_workers: 8
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10081
dist_backend: nccl
gpu: 0
use_pretrain: True
pretrain_path: saved_models/usb_cv/fullysupervised_photo_200000_lr5e5/model_best.pth
source_domain: photo
train_on_sources_domain: False
augmentation: cyclemix