algorithm: ent
save_dir: ./saved_models/usb_cv/
save_name: ent_domainnet_20_10label_sketch_multi_domain_1
resume: True
load_path: ./saved_models/usb_cv/ent_domainnet_20_10label_sketch_multi_domain/latest_model.pth
overwrite: False
use_tensorboard: True
use_wandb: False
epoch: 40
num_train_iter: 40000
num_log_iter: 256
num_eval_iter: 2048
batch_size: 16
eval_batch_size: 64
num_warmup_iter: 5000
num_labels: 3450
uratio: 1
ema_m: 0.0
hard_label: True
T: 1.0
p_cutoff: 0.95
ulb_loss_ratio: 1.0
ent_loss_ratio: 1.0
unsup_warm_up: 0.4
img_size: 224
crop_ratio: 1
optim: AdamW
lr: 0.003
layer_decay: 0.5
momentum: 0.9
weight_decay: 0.0005
amp: False
clip: 0.0
use_cat: True
net: vit_small_patch16_224
net_from_name: False
data_dir: ./data
dataset: domainnet
train_sampler: RandomSampler
num_classes: 345
num_workers: 4
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10031
dist_backend: nccl
gpu: 0
use_pretrain: True
pretrain_path: saved_models/usb_cv/fullysupervised_domainnet_sketch_pretrained_50_0/model_best.pth
# Multi-domain flag
source_domain: sketch
train_on_sources_domain: False
multi_domain_target: True
target_val_shot: 3