algorithm: adamatch
save_dir: ./saved_models/usb_cv/
save_name: adamatch_pacs_art_painting_50_4label
resume: False
load_path: ./saved_models/usb_cv/adamatch_pacs_art_painting_50_4label/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 30
num_train_iter: 30000
num_log_iter: 256
num_eval_iter: 2048
batch_size: 8
eval_batch_size: 8
num_warmup_iter: 5120
num_labels: 28
uratio: 1
ema_m: 0.00
hard_label: True
T: 0.5
ema_p: 0.999
ent_loss_ratio: 0.005
ulb_loss_ratio: 1.0
crossdomain_loss_ratio: 0.0
contrastive_loss_ratio: 0.001
warmup_kl_iter: 10000
warmup_contrastive_iter: 6000
img_size: 224
crop_ratio: 0.875
optim: AdamW
lr: 0.0005
layer_decay: 0.5
momentum: 0.9
weight_decay: 0.0005
amp: False
clip: 0.0
use_ema: True
use_cat: True
net: vit_small_patch16_224
net_from_name: False
data_dir: ./data
dataset: pacs
train_sampler: RandomSampler
num_classes: 7
num_workers: 4
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10081
dist_backend: nccl
gpu: 0
use_pretrain: True
pretrain_path: saved_models/usb_cv/fullysupervised_art_painting_200000_lr5e5/model_best.pth
source_domain: art_painting
train_on_sources_domain: False
use_fact_augment: True